consumer_key = 'key'
consumer_secret = 'secret'
request_token_URL = 'https://api.twitter.com/oauth/request_token'
authorize_URL = 'https://api.twitter.com/oauth/authorize'
access_token_URL = 'https://api.twitter.com/oauth/access_token'
callback_URL = 'http://open-lsh.datathinks.org/twitter_callback'#'https://gae-fb-canvas.appspot.com/twitter_callback'
