consumer_key = 'NunJHorV1idtYRfPrOQYvw'
consumer_secret = 'MA0MZOs4axu5QWiCqAKwZ65Dn3bBxwEemkBjoRa14'
request_token_URL = 'https://api.twitter.com/oauth/request_token'
authorize_URL = 'https://api.twitter.com/oauth/authorize'
access_token_URL = 'https://api.twitter.com/oauth/access_token'
callback_URL = 'https://open_lsh.appspot.com/twitter_callback'#'https://gae-fb-canvas.appspot.com/twitter_callback'
